export const POOKA_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_priceOracle", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "int256",
        name: "fundingRate",
        type: "int256",
      },
      {
        indexed: false,
        internalType: "int256",
        name: "cumulativeIndex",
        type: "int256",
      },
    ],
    name: "FundingUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "maxLeverage",
        type: "uint256",
      },
    ],
    name: "MarketAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      { indexed: false, internalType: "int256", name: "pnl", type: "int256" },
      {
        indexed: false,
        internalType: "int256",
        name: "fundingPaid",
        type: "int256",
      },
    ],
    name: "PositionClosed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      { indexed: false, internalType: "int256", name: "pnl", type: "int256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "liquidationPrice",
        type: "uint256",
      },
    ],
    name: "PositionLiquidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "size",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "collateral",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "entryPrice",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "isLong", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "leverage",
        type: "uint256",
      },
    ],
    name: "PositionOpened",
    type: "event",
  },
  {
    inputs: [],
    name: "BASE_FUNDING_RATE",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FUNDING_INTERVAL",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LIQUIDATION_THRESHOLD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_LEVERAGE_DEFAULT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRECISION",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRICE_STALENESS_THRESHOLD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "uint256", name: "maxLeverage", type: "uint256" },
      { internalType: "uint256", name: "maintenanceMargin", type: "uint256" },
    ],
    name: "addMarket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "balances",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "string", name: "symbol", type: "string" },
    ],
    name: "canLiquidate",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "symbol", type: "string" }],
    name: "closePosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "symbol", type: "string" }],
    name: "getMarket",
    outputs: [
      { internalType: "uint256", name: "currentPrice", type: "uint256" },
      { internalType: "uint256", name: "priceTimestamp", type: "uint256" },
      { internalType: "int256", name: "fundingRate", type: "int256" },
      { internalType: "uint256", name: "totalLongSize", type: "uint256" },
      { internalType: "uint256", name: "totalShortSize", type: "uint256" },
      { internalType: "uint256", name: "maxLeverage", type: "uint256" },
      { internalType: "bool", name: "isActive", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMarketSymbols",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    name: "getPosition",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "symbol", type: "string" }
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "size", type: "uint256" },
          { name: "collateral", type: "uint256" },
          { name: "entryPrice", type: "uint256" },
          { name: "leverage", type: "uint256" },
          { name: "isLong", type: "bool" },
          { name: "isOpen", type: "bool" },
          { name: "currentPrice", type: "uint256" },
          { name: "liquidationPrice", type: "uint256" },
          { name: "unrealizedPnL", type: "int256" },
          { name: "netPnL", type: "int256" },
          { name: "canBeLiquidated", type: "bool" },
        ]
      }
    ]
  }
  ,
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "string", name: "symbol", type: "string" },
    ],
    name: "getPositionPnL",
    outputs: [
      {
        components: [
          { internalType: "int256", name: "unrealizedPnL", type: "int256" },
          { internalType: "int256", name: "fundingPayment", type: "int256" },
          { internalType: "int256", name: "netPnL", type: "int256" },
        ],
        internalType: "struct CrossChainPerps.PnLInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "string", name: "symbol", type: "string" },
    ],
    name: "liquidatePosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "marketSymbols",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "markets",
    outputs: [
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "uint256", name: "maxLeverage", type: "uint256" },
      { internalType: "uint256", name: "maintenanceMargin", type: "uint256" },
      { internalType: "int256", name: "fundingRate", type: "int256" },
      {
        internalType: "int256",
        name: "cumulativeFundingIndex",
        type: "int256",
      },
      { internalType: "uint256", name: "lastFundingTime", type: "uint256" },
      { internalType: "uint256", name: "totalLongSize", type: "uint256" },
      { internalType: "uint256", name: "totalShortSize", type: "uint256" },
      { internalType: "bool", name: "isActive", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "uint256", name: "collateralAmount", type: "uint256" },
      { internalType: "uint256", name: "leverage", type: "uint256" },
      { internalType: "bool", name: "isLong", type: "bool" },
    ],
    name: "openPosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "string", name: "", type: "string" },
    ],
    name: "positions",
    outputs: [
      { internalType: "uint256", name: "size", type: "uint256" },
      { internalType: "uint256", name: "collateral", type: "uint256" },
      { internalType: "uint256", name: "entryPrice", type: "uint256" },
      { internalType: "int256", name: "fundingIndex", type: "int256" },
      { internalType: "bool", name: "isLong", type: "bool" },
      { internalType: "bool", name: "isOpen", type: "bool" },
      { internalType: "uint256", name: "lastUpdateTime", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "priceOracle",
    outputs: [
      { internalType: "contract PriceOracle", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_priceOracle", type: "address" },
    ],
    name: "setPriceOracle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "symbol", type: "string" }],
    name: "toggleMarket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "symbol", type: "string" }],
    name: "updateFunding",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
